# Generated by Django 4.0.3 on 2022-10-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cate_name',
            new_name='category_name',
        ),
    ]
