# Generated by Django 4.0.3 on 2022-10-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_app', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
