# Generated by Django 4.0.3 on 2022-10-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_app', '0005_rename_user_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
