# Generated by Django 4.0.3 on 2022-10-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_app', '0007_alter_customer_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
